In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Fertilizer Prediction.csv')
df.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0           26         52        38     Sandy      Maize        37          0   
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   
3           32         62        34       Red    Tobacco        22          0   
4           28         54        46    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14  
3           20           28-28  
4            0            Urea

In [3]:
drop = df[df.columns[6:8]]

In [4]:
drop.head()

Potassium  Phosphorous
0          0            0
1          0           36
2          9           30
3          0           20
4          0            0

In [5]:
df1 = df.drop(drop, axis=1)

In [6]:
df1.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  \
0           26         52        38     Sandy      Maize        37   
1           29         52        45     Loamy  Sugarcane        12   
2           34         65        62     Black     Cotton         7   
3           32         62        34       Red    Tobacco        22   
4           28         54        46    Clayey      Paddy        35   

  Fertilizer Name  
0            Urea  
1             DAP  
2        14-35-14  
3           28-28  
4            Urea

In [7]:
soil = list(np.unique(df1['Soil Type']))
soil

['Black', 'Clayey', 'Loamy', 'Red', 'Sandy']

In [8]:
crop = list(np.unique(df1['Crop Type']))
crop

['Barley',
 'Cotton',
 'Ground Nuts',
 'Maize',
 'Millets',
 'Oil seeds',
 'Paddy',
 'Pulses',
 'Sugarcane',
 'Tobacco',
 'Wheat']

In [9]:
df1['Soil Type'].replace(['Black', 'Clayey', 'Loamy', 'Red', 'Sandy'], [1,2,3,4,5], inplace=True)
df1['Crop Type'].replace(['Barley',
 'Cotton',
 'Ground Nuts',
 'Maize',
 'Millets',
 'Oil seeds',
 'Paddy',
 'Pulses',
 'Sugarcane',
 'Tobacco',
 'Wheat'], [1,2,3,4,5,6,7,8,9,10,11], inplace=True)

In [10]:
df1.head()

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0           26         52        38          5          4        37   
1           29         52        45          3          9        12   
2           34         65        62          1          2         7   
3           32         62        34          4         10        22   
4           28         54        46          2          7        35   

  Fertilizer Name  
0            Urea  
1             DAP  
2        14-35-14  
3           28-28  
4            Urea

In [11]:
X = df1[df1.columns[:6]]

In [12]:
y = df1['Fertilizer Name']

In [13]:
X.head()

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen
0           26         52        38          5          4        37
1           29         52        45          3          9        12
2           34         65        62          1          2         7
3           32         62        34          4         10        22
4           28         54        46          2          7        35

In [14]:
y.head()

0        Urea
1         DAP
2    14-35-14
3       28-28
4        Urea
Name: Fertilizer Name, dtype: object

In [15]:
X.groupby(by=y)

In [16]:
X.groupby(by=y).mean()

Temparature  Humidity    Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                            
10-26-26           29.714286  58.142857  39.285714   3.142857   7.857143   
14-35-14           31.357143  61.142857  45.214286   2.857143   5.571429   
17-17-17           29.000000  57.571429  47.142857   3.571429   5.285714   
20-20              29.142857  57.571429  45.285714   2.714286   7.071429   
28-28              29.529412  58.117647  41.941176   3.352941   6.294118   
DAP                31.833333  61.333333  42.611111   3.444444   4.944444   
Urea               30.227273  58.727273  41.954545   2.454545   6.545455   

                  Nitrogen  
Fertilizer Name             
10-26-26          7.571429  
14-35-14          8.214286  
17-17-17         12.142857  
20-20            11.214286  
28-28            22.647059  
DAP              12.944444  
Urea             38.363636

In [17]:
X.groupby(by=y).var()

Temparature  Humidity     Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                             
10-26-26           16.238095  44.809524   75.904762   1.476190  11.142857   
14-35-14           10.401099  24.593407  187.565934   2.131868   9.802198   
17-17-17           13.000000  43.285714  160.476190   1.952381  12.904762   
20-20              11.054945  31.340659  140.373626   2.373626   5.609890   
28-28              10.389706  29.985294   60.183824   2.117647  11.970588   
DAP                12.852941  33.529412  168.016340   1.673203  10.996732   
Urea               12.469697  38.779221  121.378788   1.783550   8.164502   

                  Nitrogen  
Fertilizer Name             
10-26-26         12.285714  
14-35-14          1.719780  
17-17-17          3.142857  
20-20             3.565934  
28-28             1.367647  
DAP               2.408497  
Urea              5.099567

In [18]:
X.groupby(by=y).std()

Temparature  Humidity    Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                            
10-26-26            4.029652   6.693992   8.712334   1.214986   3.338092   
14-35-14            3.225073   4.959174  13.695471   1.460092   3.130846   
17-17-17            3.605551   6.579188  12.667920   1.397276   3.592320   
20-20               3.324898   5.598273  11.847938   1.540658   2.368521   
28-28               3.223307   5.475883   7.757823   1.455214   3.459854   
DAP                 3.585100   5.790459  12.962112   1.293523   3.316132   
Urea                3.531246   6.227296  11.017204   1.335496   2.857359   

                 Nitrogen  
Fertilizer Name            
10-26-26         3.505098  
14-35-14         1.311404  
17-17-17         1.772811  
20-20            1.888368  
28-28            1.169464  
DAP              1.551933  
Urea             2.258222

In [19]:
def fit(X, y):
    mean = X.groupby(by=y).mean()
    var = X.groupby(by=y).var()
    std = X.groupby(by=y).std()
    return mean, var, std

In [20]:
mean, var, std = fit(X, y)

In [21]:
mean

Temparature  Humidity    Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                            
10-26-26           29.714286  58.142857  39.285714   3.142857   7.857143   
14-35-14           31.357143  61.142857  45.214286   2.857143   5.571429   
17-17-17           29.000000  57.571429  47.142857   3.571429   5.285714   
20-20              29.142857  57.571429  45.285714   2.714286   7.071429   
28-28              29.529412  58.117647  41.941176   3.352941   6.294118   
DAP                31.833333  61.333333  42.611111   3.444444   4.944444   
Urea               30.227273  58.727273  41.954545   2.454545   6.545455   

                  Nitrogen  
Fertilizer Name             
10-26-26          7.571429  
14-35-14          8.214286  
17-17-17         12.142857  
20-20            11.214286  
28-28            22.647059  
DAP              12.944444  
Urea             38.363636

In [22]:
std

Temparature  Humidity    Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                            
10-26-26            4.029652   6.693992   8.712334   1.214986   3.338092   
14-35-14            3.225073   4.959174  13.695471   1.460092   3.130846   
17-17-17            3.605551   6.579188  12.667920   1.397276   3.592320   
20-20               3.324898   5.598273  11.847938   1.540658   2.368521   
28-28               3.223307   5.475883   7.757823   1.455214   3.459854   
DAP                 3.585100   5.790459  12.962112   1.293523   3.316132   
Urea                3.531246   6.227296  11.017204   1.335496   2.857359   

                 Nitrogen  
Fertilizer Name            
10-26-26         3.505098  
14-35-14         1.311404  
17-17-17         1.772811  
20-20            1.888368  
28-28            1.169464  
DAP              1.551933  
Urea             2.258222

In [23]:
var

Temparature  Humidity     Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                             
10-26-26           16.238095  44.809524   75.904762   1.476190  11.142857   
14-35-14           10.401099  24.593407  187.565934   2.131868   9.802198   
17-17-17           13.000000  43.285714  160.476190   1.952381  12.904762   
20-20              11.054945  31.340659  140.373626   2.373626   5.609890   
28-28              10.389706  29.985294   60.183824   2.117647  11.970588   
DAP                12.852941  33.529412  168.016340   1.673203  10.996732   
Urea               12.469697  38.779221  121.378788   1.783550   8.164502   

                  Nitrogen  
Fertilizer Name             
10-26-26         12.285714  
14-35-14          1.719780  
17-17-17          3.142857  
20-20             3.565934  
28-28             1.367647  
DAP               2.408497  
Urea              5.099567

In [24]:
m = np.array(mean)
v = np.array(var)
std2 = np.array(std)

In [25]:
m

array([[29.71428571, 58.14285714, 39.28571429,  3.14285714,  7.85714286,
         7.57142857],
       [31.35714286, 61.14285714, 45.21428571,  2.85714286,  5.57142857,
         8.21428571],
       [29.        , 57.57142857, 47.14285714,  3.57142857,  5.28571429,
        12.14285714],
       [29.14285714, 57.57142857, 45.28571429,  2.71428571,  7.07142857,
        11.21428571],
       [29.52941176, 58.11764706, 41.94117647,  3.35294118,  6.29411765,
        22.64705882],
       [31.83333333, 61.33333333, 42.61111111,  3.44444444,  4.94444444,
        12.94444444],
       [30.22727273, 58.72727273, 41.95454545,  2.45454545,  6.54545455,
        38.36363636]])

In [26]:
v

array([[ 16.23809524,  44.80952381,  75.9047619 ,   1.47619048,
         11.14285714,  12.28571429],
       [ 10.4010989 ,  24.59340659, 187.56593407,   2.13186813,
          9.8021978 ,   1.71978022],
       [ 13.        ,  43.28571429, 160.47619048,   1.95238095,
         12.9047619 ,   3.14285714],
       [ 11.05494505,  31.34065934, 140.37362637,   2.37362637,
          5.60989011,   3.56593407],
       [ 10.38970588,  29.98529412,  60.18382353,   2.11764706,
         11.97058824,   1.36764706],
       [ 12.85294118,  33.52941176, 168.01633987,   1.67320261,
         10.99673203,   2.40849673],
       [ 12.46969697,  38.77922078, 121.37878788,   1.78354978,
          8.16450216,   5.0995671 ]])

In [27]:
std2

array([[ 4.029652  ,  6.69399162,  8.7123339 ,  1.21498579,  3.33809184,
         3.50509833],
       [ 3.22507347,  4.95917398, 13.6954713 ,  1.46009182,  3.13084618,
         1.31140391],
       [ 3.60555128,  6.57918797, 12.66791974,  1.39727626,  3.59231985,
         1.77281052],
       [ 3.32489775,  5.59827289, 11.84793764,  1.54065777,  2.36852066,
         1.8883681 ],
       [ 3.22330667,  5.47588295,  7.75782338,  1.45521375,  3.45985379,
         1.16946443],
       [ 3.58509988,  5.79045868, 12.96211171,  1.29352333,  3.31613209,
         1.55193322],
       [ 3.53124581,  6.22729643, 11.01720418,  1.33549608,  2.8573593 ,
         2.25822211]])

In [28]:
#looping mean and var

for i in range(len(m)):
    m_row = m[i] #the first row the next row of mean
    v_row = v[i] #the first row of variance
    for index, value in enumerate(m_row):
        mean = value
        var = v_row[index]
        print(f'mean: {mean}, var: {var}')

mean: 29.714285714285715, var: 16.238095238095234
mean: 58.142857142857146, var: 44.80952380952382
mean: 39.285714285714285, var: 75.90476190476191
mean: 3.142857142857143, var: 1.4761904761904763
mean: 7.857142857142857, var: 11.142857142857144
mean: 7.571428571428571, var: 12.285714285714285
mean: 31.357142857142858, var: 10.401098901098909
mean: 61.142857142857146, var: 24.5934065934066
mean: 45.214285714285715, var: 187.56593406593404
mean: 2.857142857142857, var: 2.131868131868132
mean: 5.571428571428571, var: 9.802197802197801
mean: 8.214285714285714, var: 1.71978021978022
mean: 29.0, var: 12.999999999999998
mean: 57.57142857142857, var: 43.285714285714306
mean: 47.142857142857146, var: 160.47619047619045
mean: 3.5714285714285716, var: 1.9523809523809526
mean: 5.285714285714286, var: 12.904761904761907
mean: 12.142857142857142, var: 3.1428571428571423
mean: 29.142857142857142, var: 11.054945054945053
mean: 57.57142857142857, var: 31.34065934065935
mean: 45.285714285714285, var: 1

In [29]:
mean_var = []

for i in range(len(m)):
    m_row = m[i]
    v_row = v[i]
    for index, value in enumerate(m_row):
        mean = value
        var = v_row[index]
        mean_var.append([mean, var])

In [30]:
mean_var

[[29.714285714285715, 16.238095238095234],
 [58.142857142857146, 44.80952380952382],
 [39.285714285714285, 75.90476190476191],
 [3.142857142857143, 1.4761904761904763],
 [7.857142857142857, 11.142857142857144],
 [7.571428571428571, 12.285714285714285],
 [31.357142857142858, 10.401098901098909],
 [61.142857142857146, 24.5934065934066],
 [45.214285714285715, 187.56593406593404],
 [2.857142857142857, 2.131868131868132],
 [5.571428571428571, 9.802197802197801],
 [8.214285714285714, 1.71978021978022],
 [29.0, 12.999999999999998],
 [57.57142857142857, 43.285714285714306],
 [47.142857142857146, 160.47619047619045],
 [3.5714285714285716, 1.9523809523809526],
 [5.285714285714286, 12.904761904761907],
 [12.142857142857142, 3.1428571428571423],
 [29.142857142857142, 11.054945054945053],
 [57.57142857142857, 31.34065934065935],
 [45.285714285714285, 140.37362637362642],
 [2.7142857142857144, 2.3736263736263736],
 [7.071428571428571, 5.609890109890109],
 [11.214285714285714, 3.5659340659340653],
 [

In [31]:
#splitting lists into various classes
mean_var2 = np.array(mean_var)
mean_var2

array([[ 29.71428571,  16.23809524],
       [ 58.14285714,  44.80952381],
       [ 39.28571429,  75.9047619 ],
       [  3.14285714,   1.47619048],
       [  7.85714286,  11.14285714],
       [  7.57142857,  12.28571429],
       [ 31.35714286,  10.4010989 ],
       [ 61.14285714,  24.59340659],
       [ 45.21428571, 187.56593407],
       [  2.85714286,   2.13186813],
       [  5.57142857,   9.8021978 ],
       [  8.21428571,   1.71978022],
       [ 29.        ,  13.        ],
       [ 57.57142857,  43.28571429],
       [ 47.14285714, 160.47619048],
       [  3.57142857,   1.95238095],
       [  5.28571429,  12.9047619 ],
       [ 12.14285714,   3.14285714],
       [ 29.14285714,  11.05494505],
       [ 57.57142857,  31.34065934],
       [ 45.28571429, 140.37362637],
       [  2.71428571,   2.37362637],
       [  7.07142857,   5.60989011],
       [ 11.21428571,   3.56593407],
       [ 29.52941176,  10.38970588],
       [ 58.11764706,  29.98529412],
       [ 41.94117647,  60.18382353],
 

In [32]:
n_class = len(np.unique(y))
n_class

7

In [33]:
#separate mean variance by class
s = np.vsplit(mean_var2, n_class)
s

[array([[29.71428571, 16.23809524],
        [58.14285714, 44.80952381],
        [39.28571429, 75.9047619 ],
        [ 3.14285714,  1.47619048],
        [ 7.85714286, 11.14285714],
        [ 7.57142857, 12.28571429]]),
 array([[ 31.35714286,  10.4010989 ],
        [ 61.14285714,  24.59340659],
        [ 45.21428571, 187.56593407],
        [  2.85714286,   2.13186813],
        [  5.57142857,   9.8021978 ],
        [  8.21428571,   1.71978022]]),
 array([[ 29.        ,  13.        ],
        [ 57.57142857,  43.28571429],
        [ 47.14285714, 160.47619048],
        [  3.57142857,   1.95238095],
        [  5.28571429,  12.9047619 ],
        [ 12.14285714,   3.14285714]]),
 array([[ 29.14285714,  11.05494505],
        [ 57.57142857,  31.34065934],
        [ 45.28571429, 140.37362637],
        [  2.71428571,   2.37362637],
        [  7.07142857,   5.60989011],
        [ 11.21428571,   3.56593407]]),
 array([[29.52941176, 10.38970588],
        [58.11764706, 29.98529412],
        [41.94117647

In [34]:
sample = [29, 58, 57, 1, 9, 12]

#combine 

for i in range(n_class):
    #first class
    class_one = s[i]
    for i in range(len(class_one)):
        #first row/value in class one
        class_one_x_mean = class_one[i][0]
        class_one_x_var = class_one[i][1]
        x_values = sample[i]
        print([class_one_x_mean, class_one_x_var, x_values])

[29.714285714285715, 16.238095238095234, 29]
[58.142857142857146, 44.80952380952382, 58]
[39.285714285714285, 75.90476190476191, 57]
[3.142857142857143, 1.4761904761904763, 1]
[7.857142857142857, 11.142857142857144, 9]
[7.571428571428571, 12.285714285714285, 12]
[31.357142857142858, 10.401098901098909, 29]
[61.142857142857146, 24.5934065934066, 58]
[45.214285714285715, 187.56593406593404, 57]
[2.857142857142857, 2.131868131868132, 1]
[5.571428571428571, 9.802197802197801, 9]
[8.214285714285714, 1.71978021978022, 12]
[29.0, 12.999999999999998, 29]
[57.57142857142857, 43.285714285714306, 58]
[47.142857142857146, 160.47619047619045, 57]
[3.5714285714285716, 1.9523809523809526, 1]
[5.285714285714286, 12.904761904761907, 9]
[12.142857142857142, 3.1428571428571423, 12]
[29.142857142857142, 11.054945054945053, 29]
[57.57142857142857, 31.34065934065935, 58]
[45.285714285714285, 140.37362637362642, 57]
[2.7142857142857144, 2.3736263736263736, 1]
[7.071428571428571, 5.609890109890109, 9]
[11.214

In [35]:
np.e

2.718281828459045

In [36]:
#building the equation
def gnb(x_val, x_mean, x_var):
    """GNB = Gausian Naive Bayes
      x_val = x from sample
      x_mean = mean for the class and feature in question
      x_var = variance for the class and feature in question
      x_mean and x_var need to corresnpond to the right x_val feature
    """
    
    #variance
    variance = x_var
    
    #mean
    mean = x_mean
    
    #natural log
    e = np.e
    
    #pi
    pi = np.pi
    
    #first part equation
    equation_1 = 1/(np.sqrt(2 * pi * variance))
    
    #second part equation
    
    #denominator
    denom = 2 * variance
    
    #numerator calc
    numerator = (x_val - mean) ** 2
    
    #exponent
    expo = np.exp(-(numerator/denom))
    
    #probability
    prob = equation_1 * expo
    
    return prob

In [37]:
prob = []

for i in range(n_class):
    #first class
    class_one = s[i]
    for i in range(len(class_one)):
        #first row/value in class one
        class_one_x_mean = class_one[i][0]
        class_one_x_var = class_one[i][1]
        x_sample = sample[i]
        prob.append([gnb(x_sample, class_one_x_mean, class_one_x_var)])

In [38]:
prob

[[0.0974584983699923],
 [0.05958349901522936],
 [0.005795257620995652],
 [0.06932356025423449],
 [0.11270900816744109],
 [0.05123512923797086],
 [0.09470511052281971],
 [0.0658092560936892],
 [0.02011515626939535],
 [0.12168153433974714],
 [0.069958191668588],
 [0.0047162490600498284],
 [0.11064668061060755],
 [0.06050849550899817],
 [0.023266387990788315],
 [0.052505196221438274],
 [0.0650717398823302],
 [0.22430435120494258],
 [0.1198756302172873],
 [0.07105316031968872],
 [0.02065339913528099],
 [0.1394295807261511],
 [0.12091023996183399],
 [0.19374483070057064],
 [0.12210981947654304],
 [0.07283760830707306],
 [0.007815837869353458],
 [0.07417850410360752],
 [0.08492477581519098],
 [3.422057849036454e-19],
 [0.08142944956458277],
 [0.05837648937568808],
 [0.016620804766794707],
 [0.05172062853383268],
 [0.05695038570538828],
 [0.21360803617472998],
 [0.10635384253635824],
 [0.06362807244338689],
 [0.014251787122570985],
 [0.1650747339061035],
 [0.09653987909396979],
 [4.4795873032

In [39]:
b = np.array(prob)
prob_s = np.vsplit(b, n_class)

prob_s

[array([[0.0974585 ],
        [0.0595835 ],
        [0.00579526],
        [0.06932356],
        [0.11270901],
        [0.05123513]]),
 array([[0.09470511],
        [0.06580926],
        [0.02011516],
        [0.12168153],
        [0.06995819],
        [0.00471625]]),
 array([[0.11064668],
        [0.0605085 ],
        [0.02326639],
        [0.0525052 ],
        [0.06507174],
        [0.22430435]]),
 array([[0.11987563],
        [0.07105316],
        [0.0206534 ],
        [0.13942958],
        [0.12091024],
        [0.19374483]]),
 array([[1.22109819e-01],
        [7.28376083e-02],
        [7.81583787e-03],
        [7.41785041e-02],
        [8.49247758e-02],
        [3.42205785e-19]]),
 array([[0.08142945],
        [0.05837649],
        [0.0166208 ],
        [0.05172063],
        [0.05695039],
        [0.21360804]]),
 array([[1.06353843e-01],
        [6.36280724e-02],
        [1.42517871e-02],
        [1.65074734e-01],
        [9.65398791e-02],
        [4.47958730e-31]])]

In [40]:
final_prob = []

for i in prob_s:
    class_prob = np.prod(i)
    final_prob.append(class_prob)

In [41]:
final_prob

[1.3471805015702742e-08,
 5.033195406759877e-09,
 1.1937575017508392e-07,
 5.745845832525619e-07,
 1.4985858754882797e-25,
 4.971066493403125e-08,
 6.884884207504489e-37]

In [42]:
maxi_prob = max(final_prob)
maxi_prob

5.745845832525619e-07

In [43]:
prob_index = final_prob.index(maxi_prob)
prob_index

3

In [44]:
classes = np.unique(y)
classes

array(['10-26-26', '14-35-14', '17-17-17', '20-20', '28-28', 'DAP',
       'Urea'], dtype=object)

In [45]:
pred = classes[prob_index]
pred

'20-20'

In [46]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [47]:
skngb = GaussianNB()

In [48]:
skngb.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [49]:
sample_2 = np.array(sample)
sample_re = sample_2.reshape(1, -1)
sample_re

array([[29, 58, 57,  1,  9, 12]])

In [50]:
skngb.predict(sample_re)

array(['20-20'], dtype='<U8')

In [51]:
expected = y
predicted = skngb.predict(X)

In [52]:
print(metrics.classification_report(expected, predicted))

              precision    recall  f1-score   support

    10-26-26       1.00      0.57      0.73         7
    14-35-14       0.80      0.86      0.83        14
    17-17-17       0.50      0.29      0.36         7
       20-20       0.50      0.57      0.53        14
       28-28       1.00      1.00      1.00        17
         DAP       0.62      0.72      0.67        18
        Urea       1.00      1.00      1.00        22

    accuracy                           0.79        99
   macro avg       0.77      0.72      0.73        99
weighted avg       0.80      0.79      0.78        99



In [53]:
print(metrics.confusion_matrix(expected, predicted))

[[ 4  1  0  0  0  2  0]
 [ 0 12  0  2  0  0  0]
 [ 0  0  2  2  0  3  0]
 [ 0  2  1  8  0  3  0]
 [ 0  0  0  0 17  0  0]
 [ 0  0  1  4  0 13  0]
 [ 0  0  0  0  0  0 22]]
