In [53]:
import pandas as pd
import numpy as np
from sklearn import metrics
from mixed_naive_bayes import MixedNB

In [54]:
model = MixedNB()

In [55]:
dataframe = pd.read_csv('Fertilizer Prediction.csv')

In [56]:
drop = dataframe[dataframe.columns[6:8]]
df = dataframe.drop(drop, axis=1)

In [57]:
df.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  \
0           26         52        38     Sandy      Maize        37   
1           29         52        45     Loamy  Sugarcane        12   
2           34         65        62     Black     Cotton         7   
3           32         62        34       Red    Tobacco        22   
4           28         54        46    Clayey      Paddy        35   

  Fertilizer Name  
0            Urea  
1             DAP  
2        14-35-14  
3           28-28  
4            Urea

In [58]:
df['Soil Type'].replace(['Black', 'Clayey', 'Loamy', 'Red', 'Sandy'], [0,1,2,3,4], inplace=True)

In [59]:
df['Crop Type'].replace(['Barley',
 'Cotton',
 'Ground Nuts',
 'Maize',
 'Millets',
 'Oil seeds',
 'Paddy',
 'Pulses',
 'Sugarcane',
 'Tobacco',
 'Wheat'], [0,1,2,3,4,5,6,7,8,9,10], inplace=True)

In [60]:
df.head()

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0           26         52        38          4          3        37   
1           29         52        45          2          8        12   
2           34         65        62          0          1         7   
3           32         62        34          3          9        22   
4           28         54        46          1          6        35   

  Fertilizer Name  
0            Urea  
1             DAP  
2        14-35-14  
3           28-28  
4            Urea

In [61]:
X = df[df.columns[:6]]

In [62]:
y = df[df.columns[6]]

In [63]:
y.head()

0        Urea
1         DAP
2    14-35-14
3       28-28
4        Urea
Name: Fertilizer Name, dtype: object

In [64]:
y.replace(['10-26-26', '14-35-14', '17-17-17', '20-20', '28-28', 'DAP', 'Urea'], [0,1,2,3,4,5,6], inplace=True)

In [65]:
y.head()

0    6
1    5
2    1
3    4
4    6
Name: Fertilizer Name, dtype: int64

In [66]:
model = MixedNB(categorical_features=[3,4])
model.fit(X, y)

[ 5 11]


MixedNB(alpha=0.5, var_smoothing=1e-09)

In [67]:
from sklearn.model_selection import train_test_split

In [94]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=False)

In [95]:
X_train.shape

(69, 6)

In [96]:
X_test.shape

(30, 6)

In [97]:
model = MixedNB(categorical_features=[3,4])
model.fit(X_train, y_train)

[ 5 11]


MixedNB(alpha=0.5, var_smoothing=1e-09)

In [98]:
predict = model.predict(X_test)

In [99]:
from sklearn.metrics import accuracy_score

In [100]:
score = accuracy_score(y_test, predict)
score

0.5

In [101]:
print(metrics.classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.00      0.00      0.00         5
           2       0.00      0.00      0.00         0
           3       0.14      0.25      0.18         4
           4       1.00      1.00      1.00         5
           5       0.60      0.60      0.60         5
           6       1.00      1.00      1.00         6

    accuracy                           0.50        30
   macro avg       0.39      0.41      0.40        30
weighted avg       0.49      0.50      0.49        30



In [102]:
print(metrics.confusion_matrix(y_test, predict))

[[0 2 0 1 0 2 0]
 [0 0 0 5 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 3 1 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 2 0 0 3 0]
 [0 0 0 0 0 0 6]]


In [103]:
pred = pd.DataFrame(predict)
pred.replace([0,1,2,3,4,5,6], ['10-26-26', '14-35-14', '17-17-17', '20-20', '28-28', 'DAP', 'Urea'], inplace=True)
pred

0
0      20-20
1      28-28
2       Urea
3      28-28
4       Urea
5        DAP
6      20-20
7      28-28
8   17-17-17
9      20-20
10       DAP
11     20-20
12      Urea
13  17-17-17
14  17-17-17
15     28-28
16     20-20
17       DAP
18      Urea
19       DAP
20  17-17-17
21     20-20
22  14-35-14
23      Urea
24     20-20
25     28-28
26  14-35-14
27      Urea
28       DAP
29  17-17-17

In [104]:
test = pd.DataFrame(y_test)
test.replace([0,1,2,3,4,5,6], ['10-26-26', '14-35-14', '17-17-17', '20-20', '28-28', 'DAP', 'Urea'], inplace=True)
test

Fertilizer Name
69           20-20
70           28-28
71            Urea
72           28-28
73            Urea
74             DAP
75        14-35-14
76           28-28
77           20-20
78        10-26-26
79             DAP
80        14-35-14
81            Urea
82             DAP
83           20-20
84           28-28
85        14-35-14
86        10-26-26
87            Urea
88        10-26-26
89             DAP
90        14-35-14
91        10-26-26
92            Urea
93        14-35-14
94           28-28
95        10-26-26
96            Urea
97             DAP
98           20-20