In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
from mixed_naive_bayes import MixedNB

In [2]:
model = MixedNB()

In [3]:
dataframe = pd.read_csv('Fertilizer Prediction.csv')

In [4]:
drop = dataframe[dataframe.columns[6:8]]
df = dataframe.drop(drop, axis=1)

In [5]:
df.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  \
0           26         52        38     Sandy      Maize        37   
1           29         52        45     Loamy  Sugarcane        12   
2           34         65        62     Black     Cotton         7   
3           32         62        34       Red    Tobacco        22   
4           28         54        46    Clayey      Paddy        35   

  Fertilizer Name  
0            Urea  
1             DAP  
2        14-35-14  
3           28-28  
4            Urea

In [6]:
df['Soil Type'].replace(['Black', 'Clayey', 'Loamy', 'Red', 'Sandy'], [0,1,2,3,4], inplace=True)

In [7]:
df['Crop Type'].replace(['Barley',
 'Cotton',
 'Ground Nuts',
 'Maize',
 'Millets',
 'Oil seeds',
 'Paddy',
 'Pulses',
 'Sugarcane',
 'Tobacco',
 'Wheat'], [0,1,2,3,4,5,6,7,8,9,10], inplace=True)

In [8]:
df.head()

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0           26         52        38          4          3        37   
1           29         52        45          2          8        12   
2           34         65        62          0          1         7   
3           32         62        34          3          9        22   
4           28         54        46          1          6        35   

  Fertilizer Name  
0            Urea  
1             DAP  
2        14-35-14  
3           28-28  
4            Urea

In [9]:
X = df[df.columns[:6]]

In [10]:
y = df[df.columns[6]]

In [11]:
y.head()

0        Urea
1         DAP
2    14-35-14
3       28-28
4        Urea
Name: Fertilizer Name, dtype: object

In [12]:
y.replace(['10-26-26', '14-35-14', '17-17-17', '20-20', '28-28', 'DAP', 'Urea'], [0,1,2,3,4,5,6], inplace=True)

In [13]:
y.head()

0    6
1    5
2    1
3    4
4    6
Name: Fertilizer Name, dtype: int64

In [14]:
model = MixedNB(categorical_features=[3,4])
model.fit(X, y)

[ 5 11]


MixedNB(alpha=0.5, var_smoothing=1e-09)

In [15]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True)

In [35]:
X_train.shape

(69, 6)

In [36]:
X_test.shape

(30, 6)

In [37]:
model = MixedNB(categorical_features=[3,4])
model.fit(X_train, y_train)

[ 5 11]


MixedNB(alpha=0.5, var_smoothing=1e-09)

In [38]:
predict = model.predict(X_test)

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
score = accuracy_score(y_test, predict)
score

0.6

In [41]:
print(metrics.classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       1.00      0.40      0.57         5
           2       0.00      0.00      0.00         3
           3       0.00      0.00      0.00         3
           4       1.00      1.00      1.00         3
           5       0.38      0.75      0.50         4
           6       1.00      1.00      1.00        10

    accuracy                           0.60        30
   macro avg       0.48      0.45      0.44        30
weighted avg       0.65      0.60      0.60        30



In [42]:
print(metrics.confusion_matrix(y_test, predict))

[[ 0  0  0  0  0  2  0]
 [ 1  2  0  2  0  0  0]
 [ 0  0  0  2  0  1  0]
 [ 0  0  1  0  0  2  0]
 [ 0  0  0  0  3  0  0]
 [ 0  0  1  0  0  3  0]
 [ 0  0  0  0  0  0 10]]


In [43]:
pred = pd.DataFrame(predict)
pred.replace([0,1,2,3,4,5,6], ['10-26-26', '14-35-14', '17-17-17', '20-20', '28-28', 'DAP', 'Urea'], inplace=True)
pred

0
0        DAP
1       Urea
2        DAP
3      28-28
4       Urea
5       Urea
6        DAP
7      20-20
8       Urea
9        DAP
10      Urea
11     20-20
12      Urea
13  14-35-14
14       DAP
15      Urea
16      Urea
17      Urea
18     28-28
19  14-35-14
20     28-28
21       DAP
22      Urea
23  17-17-17
24  17-17-17
25  10-26-26
26     20-20
27     20-20
28       DAP
29       DAP

In [45]:
test = pd.DataFrame(y_test)
test.replace([0,1,2,3,4,5,6], ['10-26-26', '14-35-14', '17-17-17', '20-20', '28-28', 'DAP', 'Urea'], inplace=True)
test

Fertilizer Name
88        10-26-26
92            Urea
86        10-26-26
25           28-28
7             Urea
32            Urea
82             DAP
41        14-35-14
52            Urea
11        17-17-17
73            Urea
15        17-17-17
71            Urea
36        14-35-14
24           20-20
60            Urea
16            Urea
64            Urea
13           28-28
2         14-35-14
84           28-28
97             DAP
27            Urea
6            20-20
14             DAP
49        14-35-14
58        17-17-17
80        14-35-14
74             DAP
51           20-20