In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [2]:
skngb = GaussianNB()

In [3]:
dataframe = pd.read_csv('Fertilizer Prediction.csv')

In [4]:
dataframe.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0           26         52        38     Sandy      Maize        37          0   
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   
3           32         62        34       Red    Tobacco        22          0   
4           28         54        46    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14  
3           20           28-28  
4            0            Urea

In [5]:
drop = dataframe[dataframe.columns[6:8]]
df = dataframe.drop(drop, axis=1)

In [6]:
soil = list(np.unique(df['Soil Type']))
soil

['Black', 'Clayey', 'Loamy', 'Red', 'Sandy']

In [7]:
crop = list(np.unique(df['Crop Type']))
crop

['Barley',
 'Cotton',
 'Ground Nuts',
 'Maize',
 'Millets',
 'Oil seeds',
 'Paddy',
 'Pulses',
 'Sugarcane',
 'Tobacco',
 'Wheat']

In [8]:
df['Soil Type'].replace(['Black', 'Clayey', 'Loamy', 'Red', 'Sandy'], [1,2,3,4,5], inplace=True)

In [9]:
df['Crop Type'].replace(['Barley',
 'Cotton',
 'Ground Nuts',
 'Maize',
 'Millets',
 'Oil seeds',
 'Paddy',
 'Pulses',
 'Sugarcane',
 'Tobacco',
 'Wheat'], [1,2,3,4,5,6,7,8,9,10,11], inplace=True)

In [10]:
df.head()

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0           26         52        38          5          4        37   
1           29         52        45          3          9        12   
2           34         65        62          1          2         7   
3           32         62        34          4         10        22   
4           28         54        46          2          7        35   

  Fertilizer Name  
0            Urea  
1             DAP  
2        14-35-14  
3           28-28  
4            Urea

In [11]:
X = df[df.columns[:6]]

In [12]:
y = df['Fertilizer Name']

In [13]:
sample = np.array([29, 58, 57, 1, 9, 12])
sample = sample.reshape(1, -1)

In [14]:
skngb.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [15]:
print(skngb)

GaussianNB(priors=None, var_smoothing=1e-09)


In [16]:
skngb.predict(sample)

array(['20-20'], dtype='<U8')

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

In [19]:
X_train.shape

(69, 6)

In [20]:
X_test.shape

(30, 6)

In [21]:
skngb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [22]:
predict = skngb.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
score = accuracy_score(y_test, predict)

In [25]:
score

0.5

In [28]:
print(metrics.classification_report(y_test, predict))

              precision    recall  f1-score   support

    10-26-26       0.00      0.00      0.00         4
    14-35-14       0.29      0.50      0.36         4
    17-17-17       0.00      0.00      0.00         2
       20-20       0.25      0.25      0.25         4
       28-28       1.00      1.00      1.00         6
         DAP       0.50      0.50      0.50         8
        Urea       1.00      1.00      1.00         2

    accuracy                           0.50        30
   macro avg       0.43      0.46      0.44        30
weighted avg       0.47      0.50      0.48        30



In [29]:
print(metrics.confusion_matrix(y_test, predict))

[[0 3 0 0 0 1 0]
 [0 2 0 2 0 0 0]
 [0 0 0 0 0 2 0]
 [0 1 1 1 0 1 0]
 [0 0 0 0 6 0 0]
 [0 1 2 1 0 4 0]
 [0 0 0 0 0 0 2]]
