In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Fertilizer Prediction.csv')

In [3]:
df.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0           26         52        38     Sandy      Maize        37          0   
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   
3           32         62        34       Red    Tobacco        22          0   
4           28         54        46    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14  
3           20           28-28  
4            0            Urea

In [4]:
soil = list(np.unique(df['Soil Type']))
soil

['Black', 'Clayey', 'Loamy', 'Red', 'Sandy']

In [5]:
crop = list(np.unique(df['Crop Type']))
crop

['Barley',
 'Cotton',
 'Ground Nuts',
 'Maize',
 'Millets',
 'Oil seeds',
 'Paddy',
 'Pulses',
 'Sugarcane',
 'Tobacco',
 'Wheat']

In [6]:
df['Soil Type'].replace(['Black', 'Clayey', 'Loamy', 'Red', 'Sandy'], [1,2,3,4,5], inplace=True)

In [7]:
df['Crop Type'].replace(['Barley',
 'Cotton',
 'Ground Nuts',
 'Maize',
 'Millets',
 'Oil seeds',
 'Paddy',
 'Pulses',
 'Sugarcane',
 'Tobacco',
 'Wheat'], [1,2,3,4,5,6,7,8,9,10,11], inplace=True)

In [8]:
df.head()

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0           26         52        38          5          4        37   
1           29         52        45          3          9        12   
2           34         65        62          1          2         7   
3           32         62        34          4         10        22   
4           28         54        46          2          7        35   

   Potassium  Phosphorous Fertilizer Name  
0          0            0            Urea  
1          0           36             DAP  
2          9           30        14-35-14  
3          0           20           28-28  
4          0            0            Urea

In [9]:
x_values = df[df.columns[:8]]

In [10]:
y_values = df['Fertilizer Name']

In [11]:
x_values.head()

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0           26         52        38          5          4        37   
1           29         52        45          3          9        12   
2           34         65        62          1          2         7   
3           32         62        34          4         10        22   
4           28         54        46          2          7        35   

   Potassium  Phosphorous  
0          0            0  
1          0           36  
2          9           30  
3          0           20  
4          0            0

In [12]:
from sklearn.model_selection import train_test_split
X = x_values
y = y_values

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=42)

In [14]:
X.groupby(by=y)

In [15]:
X.groupby(by=y).mean()

Temparature  Humidity    Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                            
10-26-26           29.714286  58.142857  39.285714   3.142857   7.857143   
14-35-14           31.357143  61.142857  45.214286   2.857143   5.571429   
17-17-17           29.000000  57.571429  47.142857   3.571429   5.285714   
20-20              29.142857  57.571429  45.285714   2.714286   7.071429   
28-28              29.529412  58.117647  41.941176   3.352941   6.294118   
DAP                31.833333  61.333333  42.611111   3.444444   4.944444   
Urea               30.227273  58.727273  41.954545   2.454545   6.545455   

                  Nitrogen  Potassium  Phosphorous  
Fertilizer Name                                     
10-26-26          7.571429  17.714286    17.714286  
14-35-14          8.214286   8.571429    29.571429  
17-17-17         12.142857  13.000000    13.142857  
20-20            11.214286   0.000000    11.571429  
28-28            22.647059   0.000000    21.058824  
DAP              12.944444   0.000000    38.444444  
Urea             38.363636   0.000000     0.000000

In [16]:
X.groupby(by=y).var()

Temparature  Humidity     Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                             
10-26-26           16.238095  44.809524   75.904762   1.476190  11.142857   
14-35-14           10.401099  24.593407  187.565934   2.131868   9.802198   
17-17-17           13.000000  43.285714  160.476190   1.952381  12.904762   
20-20              11.054945  31.340659  140.373626   2.373626   5.609890   
28-28              10.389706  29.985294   60.183824   2.117647  11.970588   
DAP                12.852941  33.529412  168.016340   1.673203  10.996732   
Urea               12.469697  38.779221  121.378788   1.783550   8.164502   

                  Nitrogen  Potassium  Phosphorous  
Fertilizer Name                                     
10-26-26         12.285714   1.238095     5.238095  
14-35-14          1.719780   1.186813     6.417582  
17-17-17          3.142857   2.666667     2.476190  
20-20             3.565934   0.000000     6.263736  
28-28             1.367647   0.000000     7.058824  
DAP               2.408497   0.000000     4.849673  
Urea              5.099567   0.000000     0.000000

In [17]:
X.groupby(by=y).std()

Temparature  Humidity    Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                            
10-26-26            4.029652   6.693992   8.712334   1.214986   3.338092   
14-35-14            3.225073   4.959174  13.695471   1.460092   3.130846   
17-17-17            3.605551   6.579188  12.667920   1.397276   3.592320   
20-20               3.324898   5.598273  11.847938   1.540658   2.368521   
28-28               3.223307   5.475883   7.757823   1.455214   3.459854   
DAP                 3.585100   5.790459  12.962112   1.293523   3.316132   
Urea                3.531246   6.227296  11.017204   1.335496   2.857359   

                 Nitrogen  Potassium  Phosphorous  
Fertilizer Name                                    
10-26-26         3.505098   1.112697     2.288689  
14-35-14         1.311404   1.089410     2.533295  
17-17-17         1.772811   1.632993     1.573592  
20-20            1.888368   0.000000     2.502746  
28-28            1.169464   0.000000     2.656845  
DAP              1.551933   0.000000     2.202197  
Urea             2.258222   0.000000     0.000000

In [18]:
def fit(X, y):
    mean = X.groupby(by=y).mean()
    var = X.groupby(by=y).var()
    std = X.groupby(by=y).std()
    return mean, var, std

In [19]:
mean, var, std = fit(X, y)

In [20]:
mean

Temparature  Humidity    Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                            
10-26-26           29.714286  58.142857  39.285714   3.142857   7.857143   
14-35-14           31.357143  61.142857  45.214286   2.857143   5.571429   
17-17-17           29.000000  57.571429  47.142857   3.571429   5.285714   
20-20              29.142857  57.571429  45.285714   2.714286   7.071429   
28-28              29.529412  58.117647  41.941176   3.352941   6.294118   
DAP                31.833333  61.333333  42.611111   3.444444   4.944444   
Urea               30.227273  58.727273  41.954545   2.454545   6.545455   

                  Nitrogen  Potassium  Phosphorous  
Fertilizer Name                                     
10-26-26          7.571429  17.714286    17.714286  
14-35-14          8.214286   8.571429    29.571429  
17-17-17         12.142857  13.000000    13.142857  
20-20            11.214286   0.000000    11.571429  
28-28            22.647059   0.000000    21.058824  
DAP              12.944444   0.000000    38.444444  
Urea             38.363636   0.000000     0.000000

In [21]:
var

Temparature  Humidity     Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                             
10-26-26           16.238095  44.809524   75.904762   1.476190  11.142857   
14-35-14           10.401099  24.593407  187.565934   2.131868   9.802198   
17-17-17           13.000000  43.285714  160.476190   1.952381  12.904762   
20-20              11.054945  31.340659  140.373626   2.373626   5.609890   
28-28              10.389706  29.985294   60.183824   2.117647  11.970588   
DAP                12.852941  33.529412  168.016340   1.673203  10.996732   
Urea               12.469697  38.779221  121.378788   1.783550   8.164502   

                  Nitrogen  Potassium  Phosphorous  
Fertilizer Name                                     
10-26-26         12.285714   1.238095     5.238095  
14-35-14          1.719780   1.186813     6.417582  
17-17-17          3.142857   2.666667     2.476190  
20-20             3.565934   0.000000     6.263736  
28-28             1.367647   0.000000     7.058824  
DAP               2.408497   0.000000     4.849673  
Urea              5.099567   0.000000     0.000000

In [22]:
std

Temparature  Humidity    Moisture  Soil Type  Crop Type  \
Fertilizer Name                                                            
10-26-26            4.029652   6.693992   8.712334   1.214986   3.338092   
14-35-14            3.225073   4.959174  13.695471   1.460092   3.130846   
17-17-17            3.605551   6.579188  12.667920   1.397276   3.592320   
20-20               3.324898   5.598273  11.847938   1.540658   2.368521   
28-28               3.223307   5.475883   7.757823   1.455214   3.459854   
DAP                 3.585100   5.790459  12.962112   1.293523   3.316132   
Urea                3.531246   6.227296  11.017204   1.335496   2.857359   

                 Nitrogen  Potassium  Phosphorous  
Fertilizer Name                                    
10-26-26         3.505098   1.112697     2.288689  
14-35-14         1.311404   1.089410     2.533295  
17-17-17         1.772811   1.632993     1.573592  
20-20            1.888368   0.000000     2.502746  
28-28            1.169464   0.000000     2.656845  
DAP              1.551933   0.000000     2.202197  
Urea             2.258222   0.000000     0.000000

In [23]:
m = np.array(mean)
v = np.array(var)
std2 = np.array(std)

In [24]:
m

array([[29.71428571, 58.14285714, 39.28571429,  3.14285714,  7.85714286,
         7.57142857, 17.71428571, 17.71428571],
       [31.35714286, 61.14285714, 45.21428571,  2.85714286,  5.57142857,
         8.21428571,  8.57142857, 29.57142857],
       [29.        , 57.57142857, 47.14285714,  3.57142857,  5.28571429,
        12.14285714, 13.        , 13.14285714],
       [29.14285714, 57.57142857, 45.28571429,  2.71428571,  7.07142857,
        11.21428571,  0.        , 11.57142857],
       [29.52941176, 58.11764706, 41.94117647,  3.35294118,  6.29411765,
        22.64705882,  0.        , 21.05882353],
       [31.83333333, 61.33333333, 42.61111111,  3.44444444,  4.94444444,
        12.94444444,  0.        , 38.44444444],
       [30.22727273, 58.72727273, 41.95454545,  2.45454545,  6.54545455,
        38.36363636,  0.        ,  0.        ]])

In [25]:
v

array([[ 16.23809524,  44.80952381,  75.9047619 ,   1.47619048,
         11.14285714,  12.28571429,   1.23809524,   5.23809524],
       [ 10.4010989 ,  24.59340659, 187.56593407,   2.13186813,
          9.8021978 ,   1.71978022,   1.18681319,   6.41758242],
       [ 13.        ,  43.28571429, 160.47619048,   1.95238095,
         12.9047619 ,   3.14285714,   2.66666667,   2.47619048],
       [ 11.05494505,  31.34065934, 140.37362637,   2.37362637,
          5.60989011,   3.56593407,   0.        ,   6.26373626],
       [ 10.38970588,  29.98529412,  60.18382353,   2.11764706,
         11.97058824,   1.36764706,   0.        ,   7.05882353],
       [ 12.85294118,  33.52941176, 168.01633987,   1.67320261,
         10.99673203,   2.40849673,   0.        ,   4.8496732 ],
       [ 12.46969697,  38.77922078, 121.37878788,   1.78354978,
          8.16450216,   5.0995671 ,   0.        ,   0.        ]])

In [26]:
std2

array([[ 4.029652  ,  6.69399162,  8.7123339 ,  1.21498579,  3.33809184,
         3.50509833,  1.11269728,  2.28868854],
       [ 3.22507347,  4.95917398, 13.6954713 ,  1.46009182,  3.13084618,
         1.31140391,  1.08940956,  2.53329478],
       [ 3.60555128,  6.57918797, 12.66791974,  1.39727626,  3.59231985,
         1.77281052,  1.63299316,  1.57359158],
       [ 3.32489775,  5.59827289, 11.84793764,  1.54065777,  2.36852066,
         1.8883681 ,  0.        ,  2.50274574],
       [ 3.22330667,  5.47588295,  7.75782338,  1.45521375,  3.45985379,
         1.16946443,  0.        ,  2.65684466],
       [ 3.58509988,  5.79045868, 12.96211171,  1.29352333,  3.31613209,
         1.55193322,  0.        ,  2.20219736],
       [ 3.53124581,  6.22729643, 11.01720418,  1.33549608,  2.8573593 ,
         2.25822211,  0.        ,  0.        ]])

In [27]:
#looping mean and var

for i in range(len(m)):
    m_row = m[i] #the first row the next row of mean
    v_row = v[i] #the first row of variance
    for index, value in enumerate(m_row):
        mean = value
        var = v_row[index]
        print(f'mean: {mean}, var: {var}')

mean: 29.714285714285715, var: 16.238095238095234
mean: 58.142857142857146, var: 44.80952380952382
mean: 39.285714285714285, var: 75.90476190476191
mean: 3.142857142857143, var: 1.4761904761904763
mean: 7.857142857142857, var: 11.142857142857144
mean: 7.571428571428571, var: 12.285714285714285
mean: 17.714285714285715, var: 1.2380952380952381
mean: 17.714285714285715, var: 5.238095238095239
mean: 31.357142857142858, var: 10.401098901098909
mean: 61.142857142857146, var: 24.5934065934066
mean: 45.214285714285715, var: 187.56593406593404
mean: 2.857142857142857, var: 2.131868131868132
mean: 5.571428571428571, var: 9.802197802197801
mean: 8.214285714285714, var: 1.71978021978022
mean: 8.571428571428571, var: 1.1868131868131864
mean: 29.571428571428573, var: 6.417582417582414
mean: 29.0, var: 12.999999999999998
mean: 57.57142857142857, var: 43.285714285714306
mean: 47.142857142857146, var: 160.47619047619045
mean: 3.5714285714285716, var: 1.9523809523809526
mean: 5.285714285714286, var: 12

In [28]:
mean_var = []

for i in range(len(m)):
    m_row = m[i]
    v_row = v[i]
    for index, value in enumerate(m_row):
        mean = value
        var = v_row[index]
        mean_var.append([mean, var])

In [29]:
mean_var

[[29.714285714285715, 16.238095238095234],
 [58.142857142857146, 44.80952380952382],
 [39.285714285714285, 75.90476190476191],
 [3.142857142857143, 1.4761904761904763],
 [7.857142857142857, 11.142857142857144],
 [7.571428571428571, 12.285714285714285],
 [17.714285714285715, 1.2380952380952381],
 [17.714285714285715, 5.238095238095239],
 [31.357142857142858, 10.401098901098909],
 [61.142857142857146, 24.5934065934066],
 [45.214285714285715, 187.56593406593404],
 [2.857142857142857, 2.131868131868132],
 [5.571428571428571, 9.802197802197801],
 [8.214285714285714, 1.71978021978022],
 [8.571428571428571, 1.1868131868131864],
 [29.571428571428573, 6.417582417582414],
 [29.0, 12.999999999999998],
 [57.57142857142857, 43.285714285714306],
 [47.142857142857146, 160.47619047619045],
 [3.5714285714285716, 1.9523809523809526],
 [5.285714285714286, 12.904761904761907],
 [12.142857142857142, 3.1428571428571423],
 [13.0, 2.6666666666666665],
 [13.142857142857142, 2.4761904761904754],
 [29.1428571428

In [30]:
#splitting lists into various classes
mean_var2 = np.array(mean_var)
mean_var2

array([[ 29.71428571,  16.23809524],
       [ 58.14285714,  44.80952381],
       [ 39.28571429,  75.9047619 ],
       [  3.14285714,   1.47619048],
       [  7.85714286,  11.14285714],
       [  7.57142857,  12.28571429],
       [ 17.71428571,   1.23809524],
       [ 17.71428571,   5.23809524],
       [ 31.35714286,  10.4010989 ],
       [ 61.14285714,  24.59340659],
       [ 45.21428571, 187.56593407],
       [  2.85714286,   2.13186813],
       [  5.57142857,   9.8021978 ],
       [  8.21428571,   1.71978022],
       [  8.57142857,   1.18681319],
       [ 29.57142857,   6.41758242],
       [ 29.        ,  13.        ],
       [ 57.57142857,  43.28571429],
       [ 47.14285714, 160.47619048],
       [  3.57142857,   1.95238095],
       [  5.28571429,  12.9047619 ],
       [ 12.14285714,   3.14285714],
       [ 13.        ,   2.66666667],
       [ 13.14285714,   2.47619048],
       [ 29.14285714,  11.05494505],
       [ 57.57142857,  31.34065934],
       [ 45.28571429, 140.37362637],
 

In [31]:
n_class = len(np.unique(y))
n_class

7

In [32]:
#separate mean variance by class
s = np.vsplit(mean_var2, n_class)
s

[array([[29.71428571, 16.23809524],
        [58.14285714, 44.80952381],
        [39.28571429, 75.9047619 ],
        [ 3.14285714,  1.47619048],
        [ 7.85714286, 11.14285714],
        [ 7.57142857, 12.28571429],
        [17.71428571,  1.23809524],
        [17.71428571,  5.23809524]]),
 array([[ 31.35714286,  10.4010989 ],
        [ 61.14285714,  24.59340659],
        [ 45.21428571, 187.56593407],
        [  2.85714286,   2.13186813],
        [  5.57142857,   9.8021978 ],
        [  8.21428571,   1.71978022],
        [  8.57142857,   1.18681319],
        [ 29.57142857,   6.41758242]]),
 array([[ 29.        ,  13.        ],
        [ 57.57142857,  43.28571429],
        [ 47.14285714, 160.47619048],
        [  3.57142857,   1.95238095],
        [  5.28571429,  12.9047619 ],
        [ 12.14285714,   3.14285714],
        [ 13.        ,   2.66666667],
        [ 13.14285714,   2.47619048]]),
 array([[ 29.14285714,  11.05494505],
        [ 57.57142857,  31.34065934],
        [ 45.28571429,

In [33]:
sample = [30, 60, 40, 3, 3, 10]

#combine 

for i in range(n_class):
    #first class
    class_one = s[i]
    for i in range(len(class_one)):
        #first row/value in class one
        class_one_x_mean = class_one[i][0]
        class_one_x_var = class_one[i][1]
        x_values = sample[i]
        print([class_one_x_mean, class_one_x_var, x_values])

[29.714285714285715, 16.238095238095234, 30]
[58.142857142857146, 44.80952380952382, 60]
[39.285714285714285, 75.90476190476191, 40]
[3.142857142857143, 1.4761904761904763, 3]
[7.857142857142857, 11.142857142857144, 3]
[7.571428571428571, 12.285714285714285, 10]
[17.714285714285715, 1.2380952380952381, 5]
[17.714285714285715, 5.238095238095239, 10]
[31.357142857142858, 10.401098901098909, 30]
[61.142857142857146, 24.5934065934066, 60]
[45.214285714285715, 187.56593406593404, 40]
[2.857142857142857, 2.131868131868132, 3]
[5.571428571428571, 9.802197802197801, 3]
[8.214285714285714, 1.71978021978022, 10]
[8.571428571428571, 1.1868131868131864, 5]
[29.571428571428573, 6.417582417582414, 10]
[29.0, 12.999999999999998, 30]
[57.57142857142857, 43.285714285714306, 60]
[47.142857142857146, 160.47619047619045, 40]
[3.5714285714285716, 1.9523809523809526, 3]
[5.285714285714286, 12.904761904761907, 3]
[12.142857142857142, 3.1428571428571423, 10]
[13.0, 2.6666666666666665, 5]
[13.142857142857142, 

In [34]:
np.e

2.718281828459045

In [45]:
#building the equation
def gnb(x_val, x_mean, x_var):
    """GNB = Gausian Naive Bayes
      x_val = x from sample
      x_mean = mean for the class and feature in question
      x_var = variance for the class and feature in question
      x_mean and x_var need to corresnpond to the right x_val feature
    """
    
    #variance
    variance = x_var
    
    #mean
    mean = x_mean
    
    #natural log
    e = np.e
    
    #pi
    pi = np.pi
    
    #first part equation
    equation_1 = 1/(np.sqrt(2 * pi * variance))
    
    #second part equation
    
    #denominator
    denom = 2 * variance
    
    #numerator calc
    numerator = (x_val - mean) ** 2
    
    #exponent
    expo = np.exp(-(numerator/denom))
    
    #probability
    prob = equation_1 * expo
    
    return prob
    

In [46]:
#calculate the probability
sample = [30, 60, 40, 3, 3, 10, 5, 10]

prob = []

for i in range(n_class):
    #first class
    class_one = s[i]
    for i in range(len(class_one)):
        #first row/value in class one
        class_one_x_mean = class_one[i][0]
        class_one_x_var = class_one[i][1]
        x_sample = sample[i]
        prob.append([gnb(x_sample, class_one_x_mean, class_one_x_var)])

C:\Users\Admin\AppData\Local\conda\conda\envs\tensorflow_env\lib\site-packages\ipykernel_launcher.py:23: RuntimeWarning: divide by zero encountered in double_scalars
C:\Users\Admin\AppData\Local\conda\conda\envs\tensorflow_env\lib\site-packages\ipykernel_launcher.py:34: RuntimeWarning: divide by zero encountered in double_scalars
C:\Users\Admin\AppData\Local\conda\conda\envs\tensorflow_env\lib\site-packages\ipykernel_launcher.py:37: RuntimeWarning: invalid value encountered in double_scalars


In [48]:
prob

[[0.09875313109607359],
 [0.05734705554203508],
 [0.045636882557624665],
 [0.32608951188122015],
 [0.04146332693962577],
 [0.08952921079124085],
 [1.5940454298682448e-29],
 [0.0005947098147083201],
 [0.11321860712996915],
 [0.07833725069824932],
 [0.027092951862424823],
 [0.2719262714866306],
 [0.09094270022222589],
 [0.12037723132734449],
 [0.0016980892303891798],
 [1.7240130315960262e-14],
 [0.10647183909973126],
 [0.05664349631212594],
 [0.0268637633080899],
 [0.26260952626050577],
 [0.09070329389258093],
 [0.10838948832223953],
 [1.5010387947505572e-06],
 [0.03449969939610466],
 [0.11606479670717398],
 [0.06486214933540954],
 [0.030482330093124337],
 [0.25452817267511535],
 [0.03844055777695216],
 [0.1718044802977043],
 [nan],
 [0.1308838808171846],
 [0.1224559845731117],
 [0.0686746434978989],
 [0.049839581174078405],
 [0.2662011387822439],
 [0.07328425083664385],
 [1.371739533380713e-26],
 [nan],
 [2.5963396712340653e-05],
 [0.09763907817143481],
 [0.06709399295124668],
 [0.03015

In [49]:
b = np.array(prob)
prob_s = np.vsplit(b, n_class)

prob_s

[array([[9.87531311e-02],
        [5.73470555e-02],
        [4.56368826e-02],
        [3.26089512e-01],
        [4.14633269e-02],
        [8.95292108e-02],
        [1.59404543e-29],
        [5.94709815e-04]]),
 array([[1.13218607e-01],
        [7.83372507e-02],
        [2.70929519e-02],
        [2.71926271e-01],
        [9.09427002e-02],
        [1.20377231e-01],
        [1.69808923e-03],
        [1.72401303e-14]]),
 array([[1.06471839e-01],
        [5.66434963e-02],
        [2.68637633e-02],
        [2.62609526e-01],
        [9.07032939e-02],
        [1.08389488e-01],
        [1.50103879e-06],
        [3.44996994e-02]]),
 array([[0.1160648 ],
        [0.06486215],
        [0.03048233],
        [0.25452817],
        [0.03844056],
        [0.17180448],
        [       nan],
        [0.13088388]]),
 array([[1.22455985e-01],
        [6.86746435e-02],
        [4.98395812e-02],
        [2.66201139e-01],
        [7.32842508e-02],
        [1.37173953e-26],
        [           nan],
        [2

In [50]:
final_prob = []

for i in prob_s:
    class_prob = np.prod(i)
    final_prob.append(class_prob)

In [51]:
final_prob

[2.965852182901985e-39,
 2.0941456001413246e-23,
 2.166105421148533e-14,
 nan,
 nan,
 nan,
 nan]

In [52]:
maxi_prob = max(final_prob)
maxi_prob

2.166105421148533e-14

In [53]:
prob_index = final_prob.index(maxi_prob)
prob_index

2

In [54]:
classes = np.unique(y)
classes

array(['10-26-26', '14-35-14', '17-17-17', '20-20', '28-28', 'DAP',
       'Urea'], dtype=object)

In [55]:
pred = classes[prob_index]
pred

'17-17-17'

In [56]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [57]:
skngb = GaussianNB()

In [58]:
skngb.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [65]:
sample_2 = np.array(sample)
sample_re = sample_2.reshape(1, -1)
sample_re

array([[30, 60, 40,  3,  3, 10,  5, 10]])

In [66]:
skngb.predict(sample_re)

array(['17-17-17'], dtype='<U8')

In [67]:
expected = y
predicted = skngb.predict(X)

In [68]:
print(metrics.classification_report(expected, predicted))

              precision    recall  f1-score   support

    10-26-26       1.00      1.00      1.00         7
    14-35-14       1.00      1.00      1.00        14
    17-17-17       1.00      1.00      1.00         7
       20-20       1.00      1.00      1.00        14
       28-28       1.00      1.00      1.00        17
         DAP       1.00      1.00      1.00        18
        Urea       1.00      1.00      1.00        22

    accuracy                           1.00        99
   macro avg       1.00      1.00      1.00        99
weighted avg       1.00      1.00      1.00        99



In [69]:
print(metrics.confusion_matrix(expected, predicted))

[[ 7  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0 14  0  0  0]
 [ 0  0  0  0 17  0  0]
 [ 0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0 22]]
